# Generated by Django 4.0.1 on 2022-01-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_sample_register', '0002_soilsample_delete_choice_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_B',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_Cu',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_Fe',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_K2O',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_Mg',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_Mn',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_P205',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='chemical_element_Zn',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='soilsample',
            name='longitude',
        ),
    ]
