# Generated by Django 4.0.1 on 2022-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil_sample_register', '0003_remove_soilsample_chemical_element_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilsample',
            name='id',
        ),
        migrations.AddField(
            model_name='soilsample',
            name='sample_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
